### ISSUE TITLE
`Webpack 5` support 

### ISSUE THREAD

**Issue by darrikonn** [seek-oss/treat#139]
`Webpack 5` has already been released.

Are there any plans on getting this into `treat`?

**Comment by mattcompiles** [comment]
Hey Mate. 

We're definitely looking to get onto webpack 5 ASAP. Unfortunately, we're blocked due to a broken API and can't upgrade until this is resolved. The issue can be tracked here. https://github.com/webpack/webpack/issues/11269

**Comment by darrikonn** [comment]
Ahh ok nice, didn't know about the bug :+1:

**Comment by tom-sherman** [comment]
Running the TreatPlugin on Webpack 5 gives me this error

```
Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
```

I'm mainly pasting this here for users coming from google/github search.

**Comment by uptonking** [comment]
@mattcompiles webpack 5 has fixed the bug.  
U guys can start to make treat compatible with webpack 5.

**Comment by mattcompiles** [comment]
I am currently working on this. Hopefully have it out soon.

**Comment by zhongliangwang** [comment]
hi may i know the progress?

**Comment by mattcompiles** [comment]
Hi 👋 
It has been quite tricky to get the update working. However, I now have a branch with the core tests passing. I'm hoping to be able to support webpack 4 and 5 at the same time which I am validating ATM. I'm not going to commit to timelines as I may run into unexpected issues, but with everything going smoothly I'd expect a treat `v2.0.0` release that supports webpack 5 next week. 

Note that due to further webpack issues resolved as part of this process the required version will be webpack `> 5.20.2`. [Related webpack PR](https://github.com/webpack/webpack/pull/12567)
