### ISSUE TITLE
Publish next-treat v2 to npm

### ISSUE THREAD

**Issue by saevarma** [seek-oss/treat#187]
@mattcompiles could you publish new version of `next-treat` package to npm 🙏?

Current version `1.3.0` on npm uses the Treat@v1 require:
```
const TreatPlugin = require('treat/webpack-plugin');
```

While on  `master` this has been fixed for Treat@v2:
```
const { TreatPlugin } = require('treat/webpack-plugin');
```

It is on our ToDo list to migrate treat to vanilla-extract but in the meanwhile would much appreciate this publish.

**Comment by saevarma** [comment]
Any Seek member (@mattcompiles, @markdalgleish, @michaeltaranto) available to publish  `next-treat` v2 to npm?

**Comment by mattcompiles** [comment]
Hey @saevarma, The reason we didn't publish `next-treat@2.0.0` is because our tests were failing and we had no confidence at all that it works. We don't use next so it didn't feel right to publish. If you need to continue using treat I'd suggest copying the plugin source into your projects. It's only a single file so it shouldn't be a big issue.

**Comment by saevarma** [comment]
@mattcompiles  thank you for your reply. I understand and already did that for a workaround.
