### ISSUE TITLE
Rollup support?

### ISSUE THREAD

**Issue by ahtee** [seek-oss/treat#62]
Was wondering if there are any plans to expand upon this since Rollup can be used to create component libraries in React. At build time, rollup would compile the treat files and output to either the js build file or a separate CSS built file.

Just a proposal. If Webpack is the only option for now that can still work for webpack users.

**Comment by mattsjones** [comment]
Hi 👋 
We currently don't have any plans to support Rollup. We're not against having a Rollup implementation though, it's more about the time involved to create it. I'm not an expert on Rollup plugin development so it's hard to say how difficult it would be. If anyone wanted to work on a Rollup (or parcel) version I'd be happy to answer any questions they may have on [Spectrum](https://spectrum.chat/treatcss?tab=posts).

**Comment by ahtee** [comment]
Thats cool! I just wanted to open an issue in case others may have the same question or want to work on this. I am not familiar with it but after some research may take this up. :)

**Comment by maraisr** [comment]
I'm working on one atm - I'm keen to collab, if you're keen! @ahtee

**Comment by AlexGalays** [comment]
@maraisr  Any luck?

**Comment by maraisr** [comment]
Hello friends 👋 just a quick update on this. I have successfully built!! Im not quite there yet:
- Have kept the api similar to that of webpack, however instead of `test` its the classic `include`/`exclude` that we're used to with rollup plugins
- the ident tokens `hash` and alike was a copy-pasta job from loader-utils, which im not 100% happy with, so will be looking at potentially slightly different api there too.
- css emission, unlike webpack doesnt go through "loaders" again, or least I don't know about any, so will need to investigate. But that aside, the `processCss` function from treat is used, so behaviour is 100% identical to that of treat webpack.
- Unlike treat webpack, I have opted for a slightly different data structure to how local/theme styles are maintained internally which I believe _could_ solve the `@font-face` issue in the future. (its pretty much a Map rather than 2 arrays).
- Module orders, and class orders I believe to be correct from my synthetic tests, however going to write some unit tests to confirm this.
- There is 1 breaking change I will need to make to treat runtime @ https://github.com/seek-oss/treat/blob/master/packages/treat/src/resolveStyles.ts#L34 because RollUp modules emit as a `Object.freeze()` which rip out the `__proto__` also, which mean the constructor function doesn't exist. So the cloning there might either need to change, or for me to change the namespace output of rollup to export a `Proxy` like webpack does.

outside that; it seems to be 100% identical to that of webpack. I'll be reaching out to the seek folk to guide me for how we could potential keep implementation detail still exposable to rollup. They have outlined in the past that this repo won't house this plugin, so a community contract might need to be established on some treat api's.

Outside that; I will update this ticket once this does get published in something of a beta/alpha something. It is closed source at this stage, but if anyone is interested in helping out - let me know and I can add you.

**Comment by maraisr** [comment]
Looking for some beta testers!! 🎉 

```
yarn add rollup-plugin-treat@alpha

import { rollupPluginTreat } from 'rollup-plugin-treat';

/*
options:
include?: FilterPattern;							| default: /\.treat\.(ts|js)$/
exclude?: FilterPattern; 							| default: undefined
localIdentName: string; 							| default: as per treat docs
themeIdentName: (() => string) 						| string; default: as per treat docs
outputCSS: boolean | string;						| default: true (string? = fileName)
onCSSOutput(source: string): Promise<string> | string;
minify: boolean;									| defualt: isProduction
browsers: Array<string>;							| default: []
*/

export default {
	input: './myThing.js',

	plugins: [
		rollupPluginTreat({
			/* options */
		})
	]
}
```

For the time being lets track any progress here; if this starts to annoy the Seek folk we can move discussions over to [my repo](https://github.com/maraisr/rollup-plugin-treat/settings)?

There are still a couple of holes; so happy if someone wanted to get on board and help me through them!

**Comment by maraisr** [comment]
Following a conversions with @markdalgleish it seems that Seek will quite possibly be handling the "to Rollup" for us - because of this ignore my previous comments in this thread. I will halt development.
