### ISSUE TITLE
Dynamic theme creation?

### ISSUE THREAD

**Issue by KatSick** [seek-oss/treat#72]
I want to `createTheme` dynamically, so, for example, theme is defined on backend, and I retrieve it on application start.

Pseudocode:
```js
function App() {
  const { data } = useTheme(); // async load with suspense for data fetching

  return (
      <TreatProvider theme={createTheme(data.appSettings.theme)}>
        <TheamedItem />
      </TreatProvider>
  );
}
```

As I see, createTheme is returned `undefined` when I try to use it dynamically outside of `theme.treat.ts` file...

Is it supposed to work like this?

**Comment by mattsjones** [comment]
Themes must be statically known at build time. This is because all CSS is is created at build time. You can create multiple themes and swap them out at runtime (e.g. switch from dark to light theme) but you cannot create a new theme with new values. 

If you need truly dynamic theme values then you'll need a CSS-in-JS library that creates CSS client side, like emotion or styled-components.

**Comment by KatSick** [comment]
@mattsjones thank you for your answer. In any case, really great library!
