### ISSUE TITLE
How to deal with `& > *` selectors?

### ISSUE THREAD

**Issue by danielberndt** [seek-oss/treat#74]
Hey there!

first off, I was super amazed at how powerful this library is! I initially was hesitant to use it because I was afraid you couldn't use the full power of javascript to create styles via mapping and reducing over your design tokens. Instead I thought you could only use plain objects within treat files and were not able to use functions or even imports from other files as I couldn't find any examples doing this.
But I was very happy to be proven wrong! So it might be worth to be more explicit about treat's power in the docs or readme!

Now to my actual issue:

I'm trying to convert our design system from emotion to something statically extracted as performance is becoming an issue. One component looks like this `<Row spacing={2}/>`

For implementing this spacing property I would like to use a style like this:

```js
export const spacing = spacingSteps.map(val =>
  style({
    "& > *:not(:last-child)": {marginRight: `${val}rem`},
  })
)
```

but the selection validator doesn't allow me to. Now I'm a bit confused as what I'm supposed to do. My first idea would be:

```js
export const spacing = spacingSteps.map(val => style({}))

spacing.forEach(sel => globalStyle(
  `${sel} > *:not(:last-child)`,
  {marginRight: ...}
))
```

but this feels quite hacky and wrong even though it seems to work as different empty `style({})`s seems to generate different classNames (which I wasn't expecting).

So any advice and/or hints to the right spot in the docs would be greatly appreciated!

Cheers,
Daniel

**Comment by markdalgleish** [comment]
Thanks for the feedback about your experience. It's much appreciated 😄

The selector you're trying to write is technically global because it doesn't target a locally scoped class. To support cases like this, we have a `globalStyles` function: https://seek-oss.github.io/treat/styling-api#globalstyle

**Comment by markdalgleish** [comment]
Oops, sorry. Somehow missed that you're using `globalStyle` already. What you did with `globalStyle` is the correct approach.

This was a deliberate decision to enforce that each `style` call only targets a single node. In our experience, this makes for much more readable and maintainable code. Firstly, it means that you don't have to context switch while reading styles because all styles are referencing the same element (similar to a `style` prop on an element, for example). Secondly, it makes code easier to refactor because it means that when deleting a class from your component you only have to delete a single `style` call.

Hope that makes sense!

**Comment by danielberndt** [comment]
Thanks for the reply and yeah it makes sense to me :)
The fact that `style`'d calls will turn into selectors (i.e. classNames start with a `.`) within treat files already implied that this is probably the intended usage, but I wasn't quite sure either as usually `globalStyle` is normally used for 'body, html' or applying css to 3rd party libs only in my experience. 

Probably another good candidate for a guide or recipe section within your docs!
